<link href="/Users/wanghu/phenomenon/personlig/markdown/kevinburke.css" rel="stylesheet"></link>

---
title: "News: Cancer"
author: "huWANG"
date: "July 17, 2014"
output: html_document
---

# 肿瘤细胞的保护层

细胞糖萼 (覆盖细胞表面的一个糖蛋白/多糖层) 的组成通过组织分化和疾病等过程随细胞性质的变化而变化。
Valerie Weaver及同事试图弄清癌细胞中糖萼组成的变化是否会影响癌症表现型。
他们发现，大块糖萼是转移性癌细胞的一个特征，是由大型糖蛋白的生成而产生的。
大块糖萼会以物理方式将被称为“整联蛋白”或“粘合素”的糖蛋白粘附分子束缚住，后者反过来又会促进一个有利于细胞生存和增殖的信号传导体系。
临床研究显示，大型糖蛋白在来自侵袭性乳腺癌患者的循环肿瘤细胞上大量表达。
这些发现表明，糖萼及其分子组分是以使跨膜受体信号传导正常化为目的的治疗干预的有吸引力的目标。\cite{PasDuFRos1406,EwaEge1406}

***

+ [article](http://www.nature.com/nature/journal/v511/n7509/full/nature13535.html) 

> Malignancy is associated with altered expression of glycans and glycoproteins that contribute to the cellular glycocalyx.
We constructed a glycoprotein expression signature, which revealed that metastatic tumours upregulate expression of bulky glycoproteins.
A computational model predicted that these glycoproteins would influence transmembrane receptor spatial organization and function.
We tested this prediction by investigating whether bulky glycoproteins in the glycocalyx promote a tumour phenotype in human cells by increasing integrin adhesion and signalling.
Our data revealed that a bulky glycocalyx facilitates integrin clustering by funnelling active integrins into adhesions and altering integrin state by applying tension to matrix-bound integrins, independent of actomyosin contractility.
Expression of large tumour-associated glycoproteins in non-transformed mammary cells promoted focal adhesion assembly and facilitated integrin-dependent growth factor signalling to support cell growth and survival.
Clinical studies revealed that large glycoproteins are abundantly expressed on circulating tumour cells from patients with advanced disease.
Thus, a bulky glycocalyx is a feature of tumour cells that could foster metastasis by mechanically enhancing cell-surface receptor function.\cite{PasDuFRos1406}

+ [news](http://www.nature.com/nature/journal/v511/n7509/full/nature13506.html)

> Cell membranes are covered with sugar-conjugated proteins.
New findings suggest that the physical properties of this coating, which is more pronounced in cancer cells, regulate cell survival during tumour spread.\cite{EwaEge1406}

# 利用R-环来促进癌症
R-环(自然出现的三链核酸结构，由一个RNA–DNA杂合体和被取代的单链DNA组成)是基因组不稳定性的潜在诱导因素之一。
这项研究显示，TREX-2 (在“信使核糖核蛋白”(mRNP)的生物生成和输出中所涉及的一种复合物)通过与乳腺癌易感基因因子 BRCA2相互作用来处理R-环。
不含BRCA2的人细胞会积累高水平的R-环。
在肿瘤抑制因子与R-环之间的这一出乎意料的相互作用表明，R-环也许是造成复制应激和肿瘤发生的一个主要原因。\cite{BhaBarGar1406}

***

[letter](http://www.nature.com/nature/journal/v511/n7509/full/nature13374.html)

> Genome instability is central to ageing, cancer and other diseases. It is not only proteins involved in DNA replication or the DNA damage response (DDR) that are important for maintaining genome integrity: from yeast to higher eukaryotes, mutations in genes involved in pre-mRNA splicing and in the biogenesis and export of messenger ribonucleoprotein (mRNP) also induce DNA damage and genome instability. This instability is frequently mediated by R-loops formed by DNA-RNA hybrids and a displaced single-stranded DNA. Here we show that the human TREX-2 complex, which is involved in mRNP biogenesis and export, prevents genome instability as determined by the accumulation of γ-H2AX (Ser-139 phosphorylated histone H2AX) and 53BP1 foci and single-cell electrophoresis in cells depleted of the TREX-2 subunits PCID2, GANP and DSS1. We show that the BRCA2 repair factor, which binds to DSS1, also associates with PCID2 in the cell. The use of an enhanced green fluorescent protein-tagged hybrid-binding domain of RNase H1 and the S9.6 antibody did not detect R-loops in TREX-2-depleted cells, but did detect the accumulation of R-loops in BRCA2-depleted cells. The results indicate that R-loops are frequently formed in cells and that BRCA2 is required for their processing. This link between BRCA2 and RNA-mediated genome instability indicates that R-loops may be a chief source of replication stress and cancer-associated instability.\cite{BhaBarGar1406}